### ISSUE TITLE
Error when running example code.

### ISSUE THREAD

**Issue by JoshuaEworo** [tjmlabs/AgentRun#6]
I followed the Rest API Guide for AgentRun and was attempting to run the example code to simply test it out:
```
import requests

def execute_python_code(code: str) -> str:
    response = requests.post("http://localhost:8000/v1/run/", json={"code": code})
    output = response.json()["output"]
    return output


code = """
#AI generated
import yfinance as yf

# Setting the ticker and period for the last 3 days
apple = yf.Ticker('AAPL')
hist = apple.history(period="3d")

# Calculating daily moves (close - open) and their average
moves = hist['Close'] - hist['Open']
average_move = moves.mean()

print(f'{average_move:.2f}')
"""
print(execute_python_code(code))
```

but receive the following error. Any help would be appreciated.

```
OpenBLAS blas_thread_init: pthread_create failed for thread 9 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 11 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 12 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 13 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 14 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 15 of 16: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/code/script_21756bb67d4e43cb808e9488074f1830.py", line 2, in <module>
    import yfinance as yf
  File "/home/pythonuser/.local/lib/python3.12/site-packages/yfinance/__init__.py", line 23, in <module>
    from .ticker import Ticker
  File "/home/pythonuser/.local/lib/python3.12/site-packages/yfinance/ticker.py", line 27, in <module>
    import pandas as _pd
  File "/home/pythonuser/.local/lib/python3.12/site-packages/pandas/__init__.py", line 14, in <module>
    __import__(_dependency)
  File "/home/pythonuser/.local/lib/python3.12/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/home/pythonuser/.local/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/pythonuser/.local/lib/python3.12/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/pythonuser/.local/lib/python3.12/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/pythonuser/.local/lib/python3.12/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
  File "<frozen importlib._bootstrap>", line 463, in _lock_unlock_module
KeyboardInterrupt
```

**Comment by Jonathan-Adly** [comment]
This is not reproducible from my end - will keep open for a couple of days in case someone else comes across it, and will then close it down. 

My guess is this is a resource problem with your computer and yfinance. Perhaps try `code = print("hello, world")` to try and isolate the problem if it is related to this package, or something else.

<img width="1152" alt="Screenshot 2024-05-10 at 4 02 48 PM" src="https://github.com/Jonathan-Adly/AgentRun/assets/65748767/98811d7e-6d8e-40bc-97d0-1e5a2f6c91a3">
